Base:
    model_root: './checkpoints/'
    num_workers: 4
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

SimCEN:
    model: SimCEN
    dataset_id: Avazu_x4_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    hidden_units: [480, 480, 480]
    ego_hidden_activations: relu
    v1_hidden_activations: leaky_relu
    v2_hidden_activations: relu
    ego_batch_norm: False
    v1_batch_norm: False
    v2_batch_norm: False
    through_dropout: 0.1
    ego_dropout: 0
    v1_dropout: 0
    v2_dropout: 0
    alpha: 0.01
    cl_temperature: 2.0
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'